### ISSUE TITLE
Cannot connect to screencat

### ISSUE THREAD

**Issue by kernelfreak** [maxogden/screencat#64]
Hello friends,

I have installed screencat on my local Ubuntu 16.10 system. I have also installed robotjs and electron from the links given in guide. However, when I start it, it shows it has started, but no UI and no idea how to connect to it or show the html page.

This is what I see when I issue npm start

```
npm start

> screencat@4.2.0 start /usr/local/lib/node_modules/screencat
> electron electron.js

(electron) ipc module is deprecated. Use require("electron").ipcMain instead.
ready
```
How can I connect to screencat? Thank you.

**Comment by PUGE** [comment]
You can build your own server
1.install + run server
`npm install cat-lobby -g`
`cat-lobby`
2.modify `peer.js`  `var server = 'http://catlobby.maxogden.com' `  to `var server = 'http://localhost:5005'`
3.run
npm run start

**Comment by kernelfreak** [comment]
@PUGE : So, this is what I did, in node_modules directory, I installed cat-lobby via the command you provided. Then I ran it. I get in console listening on 5005. And then changed the line in peer.js, which I saw was just commented, so uncommented it. Now when I run localhost:5005, I get resource not found. Do I also need to change the remoteConfigURL to something else? I changed the first URL in it to localhost:5005, still no luck. Thank you.

**Comment by PUGE** [comment]
try
1.Clone or download https://github.com/PUGE/screenShare
2.cd screenShare
3.npm i
4.npm run lobby
5.(Create a new window) npm run start

**Comment by kernelfreak** [comment]
Hi,
Still no luck. Have a look at these images of terminal and firefox. 

1) https://postimg.org/image/73sb7z1n1/
2) https://s22.postimg.org/62s2iuknl/Screenshot_from_2017_02_16_14_28_38.png
3) https://s22.postimg.org/embgglt01/Screenshot_from_2017_02_16_14_28_44.png

**Comment by PUGE** [comment]
Are you running on mac？ Is there a cat in the upper right corner?

**Comment by kernelfreak** [comment]
@PUGE Nope, its Ubuntu Linux 16.10. No cat unfortunately anywhere on my system.

**Comment by PUGE** [comment]
Maybe this project can only run on the mac

**Comment by redanium** [comment]
@kernelfreak I'm running it on ubuntu 16.04 x64 and I got the cat in the taskbar and got the ui for sharing and joining ....etc.Otherwise, I'm having another problem related with the window to show ,telling me :
`A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read property 'show' of undefined
    at EventEmitter.<anonymous> (/home/redanium/Projects/webRTC/screencat/electron.js:49:14)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.<anonymous> (/home/redanium/Projects/webRTC/screencat/node_modules/electron-prebuilt/dist/resources/atom.asar/browser/api/web-contents.js:134:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)`

**Comment by Nebula-Spark** [comment]
@redanium Do you Found any solution after that ?,, Even i am facing the same issue !!

**Comment by bhushankummar** [comment]
Did anyone able find the solution?

**Comment by hafiztahajamil** [comment]
I face a similar problem while joining a remote screen
![image](https://user-images.githubusercontent.com/11798861/37964511-375a80ec-31db-11e8-99c2-3525e83590b2.png)
